### ISSUE TITLE
Numbers or Duration Display

### ISSUE THREAD

**Issue by conceptual2015** [wyrm65/skin.apptv#13]
Dear, 
Very happy with your great skin
I found one feature missing , which is present on other skin
On TV channels watching or Music player or Video Player and in fullscreen mode
Pressing a numeric key isn't displayed on the screen like other skin does
Might. it be possible to adjust code , or to let me know what to add 
I assume some modification shall occur in DialogSeekBar.XML file ?

thanks so much for any feedback
JP

**Comment by wyrm65** [comment]
Conceptual2015,

I thought this had been done when change was made to Kodi for its inclusion. Will investigate and make appropriate changes.

Thanks for the report
Wyrm

**Comment by conceptual2015** [comment]
My please to help ! 
Thanks for the bug fix & great skin you release
Regards
JP

**Comment by conceptual2015** [comment]
Sorry to boring again, but this doesn't work
1/ Ive applied manual the fix in the 3files , NOK
2/ I ve copied all xml file structure into mine, NOK
:-( any idea ?

**Comment by conceptual2015** [comment]
desintall skin & reinstall new one, flagged as 1.7.1 alpha still NOK :-(
tested on macos on i7 with Matrix 19.3 or  CoreELEC on S905X 
no more idea which investigation to do ...waiting advices

**Comment by wyrm65** [comment]
conceptual2015,

thought as you had posted an issue thru GitHub that you knew how to use GitHub. 

You will need to head to the skins landing page and click on the ‘code’ button and select download zip. You will have to rename the zip file to remove the “-master” from its name and then you can load the zip thru Kodi.

Github is not the place for user support, if you need to follow up you should head to the support forum listed in the Readme file, where it will be easier to provide help for you.

Wyrm
