### ISSUE TITLE
Missing "seen" and "not seen" for videos

### ISSUE THREAD

**Issue by MaxmaxOk** [wyrm65/skin.apptv#21]
**Is your feature request related to a problem? Please describe.**
After watched a video this is not marked as "seen"  [...]

**Describe the solution you'd like**
I would an overlay over the video like a checkbox.

**Describe alternatives you've considered**
add overlays for videos.

**Additional context**
other skins implements this feature.

**Comment by wyrm65** [comment]
This skin uses the Apple convention of a blue dot for 'new' items (that is unwatched items in the case of video). I extend this convention, by also showing half a dot for videos that the user has started to watch but has not completed as yet. So as such not an issue.

Also for future reference, posting issues here is probably not a great idea as I tend not to visit GitHub with any regularity. If you have a possible bug or feature request, please post something in the AppTV sub forum on the Kodi forum as you are more likely to receive a speedy response there.

**Comment by MaxmaxOk** [comment]
Sorry but there's no blue dots for videos

**Comment by wyrm65** [comment]
MaxmaxOK,

This is working fine on my system, it would be best to take this up on my Kodi sub forum at this address:

https://forum.kodi.tv/showthread.php?tid=371041

I will leave this issue open for the time being, but user support issues are best handled on the forum and not here as others can benefit from the discussion and problem solving there. Posting repeat issues here will be seen by very few and takes me away from coding.
