### ISSUE TITLE
Add the ability to remove shutdown button and header image

### ISSUE THREAD

**Issue by CHJ85** [wyrm65/skin.apptv#22]
Hi there. I just received a skin update, and all my custom changes were gone. 🙁
I'd be nice if you could add the ability to easily get rid of these things within the skin itself. The Quit button is pointless to me as I can just hit the back button twice or the S button on a keyboard. It unnecessarily takes up an icon space. And the header image is extremely pointless as it takes up 2 icon rows.
Other than that, this is a perfect skin.
Oh, and it'd also be nice if I could shrink the icons within the skin, allowing me to have 6, 7 or 8 icons in a row.
Having to do all this stuff manually for then to lose all my custom work as soon as there's an update, is a bit frustrating.
So please consider implementing these features.
Thank you.

**Comment by wyrm65** [comment]
As for the last 'Issue', please use the Kodi forums for feature requests, also one issue per issue please. Multiple issues or features makes it difficult to keep track of what has been resolved and what has not.

The 'Quit' button has been removable in the skin for a very long time now. Either from the screen settings menu (move to the left of the screen until you leave the screen) or from the Skin settings menu in the settings section of Kodi select Home Customisation. Once in that screen scroll down to the Quit button and select. In the dialog that is displayed select Action and select Disable. Done.

As to the Shelf, that is part of the Apple screen layout, which I am trying to duplicate (would be very boring without that little bit of bling). So No I am not prepared to change that.

Same applies to the number of icons across, I am duplicating the Apple look and feel. There is also the added issue of text sizing for the selected icon (text can only be as long as the width of each icon field plus one gap (1/2 the gap on each side). Now maybe for Anglophones this is plenty of space, but other languages take up additional room, so run the risk of overflowing the space set aside for them. So also No to this one as well.

As to the overwriting of your changes, make a copy of the IconHome-include.xml file and replace it anytime there is an update. Problem solved

**Comment by CHJ85** [comment]
I get that you're trying to duplicate the Apple experience. But at least allow us to remove the large logo within the skin itself.
I mean, someone like me can easily make these changes to the IconHome file. But it's not very intuitive, nor is it user-friendly.
I love your skin. But for somebody with a ton of addons in kodi, this is a bit frustrating.

**Comment by wyrm65** [comment]
Yours is the first time a request to remove the shelf part of the home screen has been made. I would say just about every user is happy with the skin as it stands. It is not worth my time to add yet another skin setting that just about every user will ignore. Please by all means clone my repo to your Kodi skin directory, change the name of the skin and make any changes you think are required (I know you have the capability to handle that). Next time I update the skin, your changes will stay intact, problem solved.
