### ISSUE TITLE
This is not an issue just a question

### ISSUE THREAD

**Issue by MadMacMig** [wyrm65/skin.apptv#7]
I was wondering how can I change the icon on the top of the screen where it says AppTV as I would just like to have a mess about and fully customize it . And also change some of the icons, like the outdated looking tv, music and film icons.

**Comment by wyrm65** [comment]
MadMacMig,

second point first, you can already change those icons from within the skin. Either navigate left on the home menu until a requester appears with the option to customise Home Screen (or us the Home customisation skin menu in the skins settings screen). Select that option and then navigate to the item you wish to change the icon for and click on the icon. Should be able to select the current icon in the requester and either select an alternative that I provided or provide your own.

first point, don’t currently allow the customisation of shelf icons, but there is no reason why I can’t add the feature in a future update. Will look into it.  If you can’t wait on this or you don’t want to make the jump to latest Kodi version you can replace the graphics in the media sub directory. Clone the skin and just replace the graphics in the above directory Will sort the first issue for you.

Now, these type of questions are best asked in my sub forum on the Kodi forum, link to my sub forum is provided in the readme.md file that is in the skins root directory (also is shown on the entry page of this GitHub). I will close this issue and answer any further questions there.

Wyrm
